sudo: required
language: node_js
node_js:
  - 10
cache: 
  directories:
    - node_modules

services:
  - docker

script:
  - docker build -t self-eck-admin-ui:latest .   
  - docker images 

deploy:
  provider: script
  script: bash docker_push
  skip_cleanup: true
  
  on:
    branch: main

branches:
  only:
  - main